### ISSUE TITLE
Link "See all tools" in frontpage takes me back to top.

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#10]
# Describe the Pain you found while using Developer Portal

Link "See all tools" in frontpage takes me back to top. Should take me to tools. 

<img width="947" alt="Näyttökuva 2020-4-1 kello 8 13 21" src="https://user-images.githubusercontent.com/1927158/78101626-c6084f00-73f0-11ea-9377-855543df256b.png">

# Indicate the importance with a number

(1. Critical, 2. Important, 3. Nice-to-have)

2.

**Comment by Nazarah** [comment]
@kyyberi  thanks for reporting the issue. Putting in in priority risk

**Comment by Nazarah** [comment]
@kyyberi  fixed and deployed in production.
