### ISSUE TITLE
Search as part of the GET

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#11]
# Describe the Pain in using this API

Would be useful to have search capability in Product API. Commonly search is implemented in listing (GET) endpoint with `q` as query parameter. Without it finding wanted products is cumbersome. 

https://api-sandbox.oftrust.net/products/v1/?q=leanheat

Would return all products in which name or description contains "leanheat". 

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)

2.

**Additional context**
<img width="839" alt="Näyttökuva 2020-4-2 kello 8 03 46" src="https://user-images.githubusercontent.com/1927158/78212623-f4516180-74b8-11ea-86b5-02f71d20122e.png">

**Comment by Nazarah** [comment]
@kyyberi  this will be scheduled as a new feature to implement as it requires API designs and making changes to the end point.

**Comment by Nazarah** [comment]
@edanchenkov  not sure if this is too let to mention, but there was a request to include a `q` as query parameter to in the GET request to search for a data product. Would return all products in which name or description contains "leanheat".

can you take a look at this?

**Comment by Nazarah** [comment]
@kyyberi this has been taken into account for the version 2 of Product API. hence closing the issue.
