### ISSUE TITLE
Can not submit for mailing list of platform of trust from https://docs.oftrust.net/

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#12]
# Describe the Pain in using this API
Can not submit for mailing list of platform of trust from https://docs.oftrust.net/

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)
2

**Additional context**
Request URL: https://platformoftrust.net/newsletter/
Request Method: GET
Status Code: 500 Internal Server Error

![image](https://user-images.githubusercontent.com/62647565/78226430-5e2b3480-74d4-11ea-8c62-e5efa86fc4e4.png)

**Comment by Nazarah** [comment]
This needs implementation from both Web_Ux team to create redirecting link with anchor to reach the specific section in Developer Portal and work from API Engine team to place the link in the 3rd column. The third column is customized for Platform of Trust documentation, so this needs to be done in a separate way then links in the n2d column.

**Comment by catalin-sbp** [comment]
@ralupopa We've fixed this, please review this at your convenience and send us your feedback - thank you.

**Comment by ralupopa** [comment]
The link is now https://developer.oftrust.net/#Help-us-achieve-the-perfect-flow-state but this shows the developer portal at the top of page, could  you check out how to actually display to user directly to Help us achieve the perfect flow state!  contact form?

**Comment by Nazarah** [comment]
@ralupopa  This part of redirecting the user to the specific section needs to be implemented by Haltu. At this point, the broken link has been fixed. This implementation would be put into a schedule based on the prioritized backlog.
