### ISSUE TITLE
Can not access generic link-link.jsonld from https://docs.oftrust.net/?python#Standards-used

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#13]
# Describe the Pain in using this API
As a developer consulting docs of Platform of Trust I need to fast get started and follow suggestions of Standards to be used. For the suggestion of using a generic link-link I can not access the context as it is no longer on github of Platform of trust.

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)
2

**Additional context**
Request URL: https://github.com/PlatformOfTrust/standards/tree/master/contexts/link-link.jsonld
Request Method: GET
Status Code: 404 Not Found

![image](https://user-images.githubusercontent.com/62647565/78231393-65a20c00-74db-11ea-8cf1-dbd22c2c44e8.png)

**Comment by catalin-sbp** [comment]
We've fixed this, please review this at your convenience and send us your feedback - thank you.

**Comment by ralupopa** [comment]
Link now going to https://standards.lifeengine.io/v1/Context/Link.jsonld Let's close this.
