### ISSUE TITLE
Broken links in documentation of Authentication section

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#14]
# Describe the Pain in using this API
From section https://docs.oftrust.net/?python#Authentication can not access  App development guide, nor the sandbox environment as it is written.

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)
2

**Additional context**
![image](https://user-images.githubusercontent.com/62647565/78261984-9ba9b500-7508-11ea-8c97-7a7c36e0f902.png)
![image](https://user-images.githubusercontent.com/62647565/78262043-af551b80-7508-11ea-95ff-cdb4b70808d8.png)

Actuallly the **Authentication code example** I find it ambiguous. Maybe it would be more clear if I see a link to that sample app from Github? Or is this a deprecated part?

**Comment by Nazarah** [comment]
@ralupopa actually descriptions shown here apart from the APIs need to be reviewed to see which sections need updates and which are no longer relevant. For quick fixes, the broken links will be mended. But later bigger task will come to review the content.

**Comment by catalin-sbp** [comment]
@ralupopa We've fixed this, please review this at your convenience and send us your feedback - thank you.

**Comment by ralupopa** [comment]
Links updated ok. I can not remove  'in progress', 'planning' tags. Please close / edit if you want
