### ISSUE TITLE
Broken links on https://platformoftrust.net/

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#15]
Pages where there are links which need to be updated (currently 500)
- https://platformoftrust.net/en/news/platform-trust-partner-program-published/ => https://platformoftrust.net/partners/?utm_campaign=Newsletter%20-%20EN&utm_source=hs_email&utm_medium=email&_hsenc=p2ANqtz--ADKBdQhMyHtBH2GrQAhcPl7eYGtmexW738Pplr8qBR3qURcEpjlYOUvuxhBEKUL8ho9JF
![image](https://user-images.githubusercontent.com/62647565/78269113-ce0be000-7511-11ea-914a-20f3f589ec6e.png)

- https://platformoftrust.net/fi/ajankohtaista/platform-of-trust-ratkoo-teknisia-kysymyksia-ja-parantaa-kehittajakokemusta-stack-overflown-avulla/ => https://platformoftrust.net/set-subscription/
![image](https://user-images.githubusercontent.com/62647565/78269322-1b884d00-7512-11ea-9aed-8bc6b01fcecd.png)

**Comment by Nazarah** [comment]
@ralupopa  Please mentions exact places where these texts and links are available. Otherwise from these screenshots, it is really difficult to identify the exact place. Please provide screenshots of the entire view with highlights on places with the broken links.

**Comment by ralupopa** [comment]
On page https://platformoftrust.net/en/news/platform-trust-partner-program-published/ there is link : platformoftrust.net/partners just under photo.
![image](https://user-images.githubusercontent.com/62647565/78530987-49f57900-77ed-11ea-82bc-5653e6da4fa9.png)

On page https://platformoftrust.net/fi/ajankohtaista/platform-of-trust-ratkoo-teknisia-kysymyksia-ja-parantaa-kehittajakokemusta-stack-overflown-avulla/ there is link for text "Pääset alkuun liittymällä postituslistallemme ja Slack-yhteisöömme" which is the last on page
![image](https://user-images.githubusercontent.com/62647565/78531169-95a82280-77ed-11ea-9f48-7c96fcd5540b.png)

**Comment by Nazarah** [comment]
@ralupopa fixed
