### ISSUE TITLE
UX | Actual links to go to expected section/header on https://docs.oftrust.net/

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#16]
# Describe the Pain in using this API
The are some links (look and feel) which do not actually redirect user to expected place. Navigation should be facilitated in order to find quickly relevant content

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)
3

**Additional context**
Just an example 
![image](https://user-images.githubusercontent.com/62647565/78282616-3dd79600-7525-11ea-8a48-ed7f9ab78510.png)

**Comment by Nazarah** [comment]
@ralupopa  This has already been taken into account. When then next feature implementation of API engine UI redesign starts, link styling will be changed in overall UI.
