### ISSUE TITLE
Improper link for Privacy Policy from mailing list form

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#17]
1. https://platformoftrust.net/en/news/platform-of-trust-uses-stack-overflow-for-technical-questions-and-overall-developer-experience-development/ click on *mailing list*
2. Form https://share.hsforms.com/18VqMobd6Rmysuai2gHkliA2pwwq?__hstc=180098363.e2807a11103a3db886652d876af7f21c.1585851006287.1585851006287.1585851006287.1&__hssc=180098363.1.1585851006287&__hsfp=1878487342 has link Privacy policy

redirected to Internal server error

**Comment by Nazarah** [comment]
@ralupopa  Please provide screenshots of the pages where the above links are. Thanks.

**Comment by ralupopa** [comment]
The above links were steps.  
Screenshot for the actual form 
![image](https://user-images.githubusercontent.com/62647565/78530049-a22b7b80-77eb-11ea-9ba9-92356e78303f.png)

**Comment by Nazarah** [comment]
@ralupopa  fixed.
