### ISSUE TITLE
Broken links from https://developer.oftrust.net/

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#18]
# Describe the Pain you found while using Developer Portal

1. Page https://developer.oftrust.net/apis/acl-api/ 
2. See Resources > API Specification

=> Both links <a href="https://raw.githubusercontent.com/PlatformOfTrust/docs/gh-pages/specs/oas/acl-api.json">here</a> and <a href="https://docs.oftrust.net/specs/raml/acl-api.zip">here</a> go to not found

![image](https://user-images.githubusercontent.com/62647565/78881631-c099ad00-7a5f-11ea-930e-bd45667b43bf.png)

1. Page https://developer.oftrust.net/apis/application/
2. See Resources > API Specification

=> Both <a href="https://raw.githubusercontent.com/PlatformOfTrust/docs/gh-pages/specs/oas/application-api.json">here</a> and <a href="https://docs.oftrust.net/specs/raml/application-api.zip">here</a> go to not found

![image](https://user-images.githubusercontent.com/62647565/78881817-00609480-7a60-11ea-8f75-762ee59213f1.png)

1. Page https://developer.oftrust.net/apis/login/
2 See Resources > API Specification

=> Both <a href="https://raw.githubusercontent.com/PlatformOfTrust/docs/gh-pages/specs/oas/login-api.json">here</a> and <a href="https://docs.oftrust.net/specs/raml/login-api.zip">here</a> go to not found

![image](https://user-images.githubusercontent.com/62647565/78882200-72d17480-7a60-11ea-8369-c8d528dc2d68.png)

# Indicate the importance with a number

(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by Nazarah** [comment]
@ralupopa  thanks for identifying the links. I have fixed them and checked the same links for rest of the APIs as well. They are working properly now.
