### ISSUE TITLE
See All use cases actually shows only the one from developer portal

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#19]
# Describe the Pain you found while using Developer Portal
On page https://developer.oftrust.net/apis/ there is section with "We love developers" where there are Tools and Use cases. When refreshing page, can see that there are presented in turn 2 tools (Insomnia and Translator) and few uses cases (some in EN, some in FI). eg : https://recordit.co/oPhfrtI9kQ
Click on "All use cases" and you are redirected to https://developer.oftrust.net/cases/ which is just showing 1 use case. The other uses cases which could have been previewed when refreshing page are on the other site, https://platformoftrust.net/en/cases/...

Given the current behavior, preview multiple cases and just showing one is misleading.

# Indicate the importance with a number
3
(1. Critical, 2. Important, 3. Nice-to-have)

Would be less confusing to show these cases in one place.

**Comment by Nazarah** [comment]
@ralupopa  In developer portal, it is designed so that only developer usecases are shown. as of now, there are two usecases in developer portal. So navigating to https://developer.oftrust.net/cases/ will give you 2 usecases.
