### ISSUE TITLE
Top of the page missing context

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#2]
# Describe the Pain you found while using Developer Portal

While loading the page for the first time, I'm shown some engine picture. It is not clear where did I land. I would love to see clear header indicating that I just entered Platform of Trust Developer Portal. In addition a small paragraph telling me what I can find from the portal. As a consumer I must understand where I am in 1-3 seconds and make a judgement is this the place for me now. 

# Indicate the importance with a number
1. 
(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by kyyberi** [comment]
Just bypass the MyWorld step, it's redundant.

**Comment by Nazarah** [comment]
@kyyberi  thanks for your feedback. The issue is already noted and will be scheduled for planning to redesign the mockup and then implement so.

**Comment by Nazarah** [comment]
@kyyberi  We have a new release in Developer Portal and this has been solved. The page now shows the title "Developer Portal" with the slogan "Flow State Experience".
