### ISSUE TITLE
Radio buttons in signing for newsletter or not in developer portal contact form

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#20]
# Describe the Pain you found while using Developer Portal

Not exactly a big pain, but still a small one. At the bottom of https://developer.oftrust.net/ is contact form. It now asks me to select from dropdown menu if I want to signup for technical newsletter. 

If that selection would be radio buttons, it would be easier to select. Having dropdown for 2 options is not convenient for user. 

<img width="642" alt="Näyttökuva 2020-4-17 kello 20 13 17" src="https://user-images.githubusercontent.com/1927158/79596029-85931b80-80e8-11ea-8d18-d85583fcf5a1.png">

# Indicate the importance with a number

(1. Critical, 2. Important, 3. Nice-to-have)

2.

**Comment by Nazarah** [comment]
@kyyberi  we are thinking about redesigning the sign up for developer newsletter. UI and actions might become different. Updates will be given when new designs are approved and scheduled for implementation.

**Comment by Nazarah** [comment]
@kyyberi  this might also to do with Hubspot form, so we'll investigate if currently radio buttons can be added here.

**Comment by Nazarah** [comment]
@kyyberi now signup for a newsletter is possible to do from Developer Portal. users need to go to the news section and click the `SIGN UP FOR NEWS` CTA to subscribe. In addition, from now on, we'll provide a link to the hubspot form to sign up for newsletter to every technical news article we publish. closing the issue for the time being.
