### ISSUE TITLE
Tools: API Engine, In the Generated API docs feedback links to old docs repo

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#21]
# Describe the bug
I tried API engine and in the resulting generated docs the feedback link points to old `docs` repo issues.

# To Reproduce
1. Go to https://apiengine.oftrust.net/
2. Input OAS file
3. Hit generate
4. Open the result from view link

# Expected behavior
Point to `consolidated-feedback` repo issues

# Screenshots
<img width="981" alt="Näyttökuva 2020-4-21 kello 17 57 58" src="https://user-images.githubusercontent.com/1927158/79881614-1aa05800-83fa-11ea-82b5-537829331652.png">

**Comment by catalin-sbp** [comment]
@ralupopa We've fixed this, please review this at your convenience and send us your feedback - thank you.

**Comment by ralupopa** [comment]
Current behavior: now when click on 'issue to Github' user is redirected to https://github.com/PlatformOfTrust/collected-feedback/issues/new?assignees=&labels=API-engine&template=api-engine-issues.md&title=%5BAPI+Engine%5D%3A 
Collected feedback is the repo where Platform of Trust wants to received feedback

**Comment by catalin-sbp** [comment]
@ralupopa As confirmed with Nazia de docs HTML should have 2 different behaviors:
* docs.oftrust.net: https://github.com/PlatformOfTrust/collected-feedback/issues/new?assignees=&labels=APIs%2C+Developer+Portal&template=api-wishlists.md&title=Wish+for+the+API
* Any docs HTML generated on apiengine.oftrust.net: https://github.com/PlatformOfTrust/collected-feedback/issues/new?assignees=&labels=API-engine&template=api-engine-issues.md&title=%5BAPI+Engine%5D%3A
