### ISSUE TITLE
Broken internal link in Defining Connector Payload Structure Guide

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#22]
# Describe the Pain you found while using Developer Portal

Defining Connector Payload Structure Guide in https://developer.oftrust.net/guides/defining-connector-payload-structure/ contains section in which is internal link "Current section is a general description. Detailed walkthrough is defined in **next section**." (that is broken, goes to 404)

<img width="920" alt="Näyttökuva 2020-4-27 kello 9 21 11" src="https://user-images.githubusercontent.com/1927158/80340164-ce756d80-8868-11ea-9363-d83922650271.png">

# Indicate the importance with a number

(1. Critical, 2. Important, 3. Nice-to-have)

2.

**Comment by Nazarah** [comment]
@kyyberi  fixed
