### ISSUE TITLE
Identity API: identity discovery query parameters are misleading

### ISSUE THREAD

**Issue by edanchenkov** [PlatformOfTrust/collected-feedback#23]
# Describe the Pain in using this API

https://docs.oftrust.net/#identities-v1-discovery too many required parameters. Only 4 is needed.

# Indicate the importance in number
Important

**Comment by Nazarah** [comment]
@edanchenkov  please provide a valid set of query parameter requirements so that the specs can be updated and published.

**Comment by edanchenkov** [comment]
Those are requiered:

```
fromId
linkContext
identityContext
linkDirection
```
