### ISSUE TITLE
Pregenerated environment with identity network for guides

### ISSUE THREAD

**Issue by edanchenkov** [PlatformOfTrust/collected-feedback#27]
# Is your suggestion for an existing guide? Or you are requesting a new guide?
It has been discussed. I believe there is a way to make sure that users will get predefined identity network for they experiments and using with guides. 

It is required for more complex guides such as a guide regarding `data product discovery` etc to skip identity network creation step. However I see small chance that making users to try to create identity network themselves at least once is a good idea if right tools are provided. Though even that should be thought through.

**Comment by Nazarah** [comment]
>However I see small chance that making users to try to create identity network themselves at least once is a good idea if right tools are provided. Though even that should be thought through.

@edanchenkov  This would be possible when the next Insomnia REST client workspace will be released. This would contain (if possible) chain requests to create a demo identity network with a given diagram. Also, a new guide for using the workspace will be published describing the process.

>there is a way to make sure that users will get predefined identity network for they experiments and using with guides.

We already have a demo identity network in `Sandbox` containing one `building`, one `floor`, 5 `room`s, temperarature `sensor` in each room and a `data product`. For the discovery purpose this demo identity network can be used provided Sandbox user has read access to it.

Would the above suffice to your request? or something more needs to be done?

**Comment by edanchenkov** [comment]
Using insomnia and chain requests might be possible, however as I remember it is not possible to store a value from 2 different requests to pass it to third one.

> For the discovery purpose this demo identity network can be used provided Sandbox user has read access to it.

Sandbox users don't have any access to such networks right now. Also it would be good if users will be able to modify this network, but then this whole thing will be almost impossible to manage. Therefore I think have a prefenerated network or provide a simple way for each user to create own basic network is a better option.

**Comment by Nazarah** [comment]
@edanchenkov  as per today's demo, it is already possible to create chain of requests in insomnia, so in the next sprint, the whole chain creation of identity network should be possible. The requests will be defined based on the demo diagram discussed during the PI planning, which would allow users to at least to create the given network using insomnia. but they may need to customize the requests themselves or try out manually creating their own network. Does it sound feasible to you?

**Comment by Nazarah** [comment]
We will 1st test with the demo identity network on how it works out. About the issue of scalability, it could be possible but given that the diagram is present. The team would try to allocate some time in the IP sprint to test with the scalability of chain-requests to accommodate creating bigger networks mimicking e.g. that of a real estate.

@catalin-sbp  do you have any feedback on this since you are leading the work?

**Comment by Nazarah** [comment]
@edanchenkov  in the **Workflow with Insomnia Workspace guide**, a section about [modifying chain requests to custom create identity network](https://developer.oftrust.net/guides/workflow-using-insomnia-workspace/#a-small-note-about-chain-requests) has been added. Developers would be able to modify the single requests for the one-click creation oof identity network under the utility folder. If we get more requests for further customizations, we will take that into account.
