### ISSUE TITLE
[API Engine]: Can not book online meeting

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#28]
**Describe the pain you are experiencing**
On page https://apiengine.oftrust.net/ there is button with 'Book online meeting', but that goes to https://platformoftrust.net/online-meeting/ which is not found.

**How urgent is this for you?**
1 from customer perspective and image

Wanted:
From API Engine to be able to reach a form or contact for meeting.

**Comment by Nazarah** [comment]
The link needs to be changed redirecting to the English site.

**Comment by ralupopa** [comment]
Can now get to https://platformoftrust.net/en/contact/
