### ISSUE TITLE
API docs internal links do not work

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#29]
# Describe the bug
In the docs.oftrust.net Getting started following internal links are not working: 
- "You should get familiar with **Authentication** process"
- "Check out the **How to get Bearer token**?"

# To Reproduce
1. Go to https://docs.oftrust.net/#Getting-started
2. Click on either one of the links mentioned above

# Expected behavior
Go to the given section in documentation. 

# Environment (please complete the following information):
 - Device: Desktop
 - OS: MacOS
 - Browser Firefox
 - Version 75.0 (64-bit)

**Comment by catalin-sbp** [comment]
@ralupopa We've performed the requested updates and deployed them to docs.oftrust.net

Please test this at your convenience and set the appropriate status for this issue - thank you.

**Comment by kyyberi** [comment]
works
