### ISSUE TITLE
Get started should go directly to registering not login

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#3]
# Describe the Pain you found while using Developer Portal

While reading the landing page, I found button "get started". That too me to login after 1 click. From there I had to find small printed "Sign up with email" and then I am at the register view. This is too cumbersome. 

**Just bypass the MyWorld step, it's redundant.**

Provide direct link from "get started" button to register form. After the registration, I should be redirected to developer.oftrust.net and somehow indicate to me that can continue now and confirmation is required (can be found from given email.). 

You might also want to consider adding "login" button next to "get started". That login button would take me to login view in sandbox. 

# Indicate the importance with a number
1.
(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by Nazarah** [comment]
@kyyberi  Thanks for your concern. This is already scheduled. FYI, at the bottom, the section "**What to do next?**" has a CTA `Try Freemium`. This would navigate you directly to the login view to the Sandbox.

**Comment by Nazarah** [comment]
We are considering to redo the website structure for both commercial and developer portal using service designing. This need will be accommodated there. Closing this issue for the time being.
