### ISSUE TITLE
API Docs Getting started  tips pointing  to old issue templates

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#30]
# Describe the Pain in using this API

In the right side of the Getting started is tips to get started. Link for feedback points to old docs repo issues. 

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)

1. 

**Additional context**

<img width="700" alt="Näyttökuva 2020-4-30 kello 18 05 25" src="https://user-images.githubusercontent.com/1927158/80726663-61cecd00-8b0d-11ea-9000-4b3a52ccd20b.png">

**Comment by Nazarah** [comment]
fixed.
