### ISSUE TITLE
Buggy links from API Profiles to API Docs

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#33]
# Describe the Pain in using this API

None of the links from API profile pages work. Open any of the API docs links under Resources and see for example: 
`https://developer.oftrust.net/apis/acl-api/`  contains link -> `https://docs.oftrust.net/#acl`

The link formatting is wrong and does not take user to the right spot in API documentation. The correct link for example in the above is `https://docs.oftrust.net/#ACL` Notice the capital lettered ACL as the anchor. 
All the anchors in the URL link must be exactly the same as the title of the given section is in API Docs. 

Fix is to check **all the links in API Profile pages** which link to API Docs and fix the formatting. 

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)

1.

**Comment by Nazarah** [comment]
@kyyberi This happened possibility because of the changes in the naming convention made to docs.oftrust.com. It's fixed now.
