### ISSUE TITLE
Links from guides toward api docs sections need update

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#34]
# Describe the Pain you found while using Developer Portal
Links from some guides from developer portal should go to a specific section of docs.oftrust.net but they are wrong, and instead of going to proper section ( broker, product) landing page is the start of docs [https://docs.oftrust.net/#Platform-of-Trust-API-Documentation](https://docs.oftrust.net/#Platform-of-Trust-API-Documentation)

On [https://developer.oftrust.net/guides/data-product-101/#what-is-a-translator-and-why-do-i-need-it](https://developer.oftrust.net/guides/data-product-101/#what-is-a-translator-and-why-do-i-need-it) 
- API documentation has href="https://docs.oftrust.net/#broker"> ; It should be https://docs.oftrust.net/#Broker in order to be redirected to Broker section from docs
- <a href="https://docs.oftrust.net/#broker">Data Broker API</a> => it is multiple times on this guide

![image](https://user-images.githubusercontent.com/62647565/81915183-ee33c200-95da-11ea-8f41-df5157c088f2.png)

![image](https://user-images.githubusercontent.com/62647565/81914976-a57c0900-95da-11ea-889f-1ebf576a9502.png)

![image](https://user-images.githubusercontent.com/62647565/81915118-d8260180-95da-11ea-8e6f-5b0e3f6c4b04.png)

![image](https://user-images.githubusercontent.com/62647565/81915372-2804c880-95db-11ea-92c3-adc977b775dc.png)

# Indicate the importance with a number
3
(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by ralupopa** [comment]
On guide [https://developer.oftrust.net/guides/register-application/](https://developer.oftrust.net/guides/register-application/)

![image](https://user-images.githubusercontent.com/62647565/81917853-6354c680-95de-11ea-8707-f5537afeb042.png)

![image](https://user-images.githubusercontent.com/62647565/81918025-a57e0800-95de-11ea-9eba-2647328ffab4.png)

This mentions product API but has link for application api endpoint
![image](https://user-images.githubusercontent.com/62647565/81918176-d3634c80-95de-11ea-9959-fca6d8822148.png)

**Comment by ralupopa** [comment]
On guide h[ttps://developer.oftrust.net/guides/technical-capabilities/](https://developer.oftrust.net/guides/technical-capabilities/)

![image](https://user-images.githubusercontent.com/62647565/81919136-1bcf3a00-95e0-11ea-89a1-e17c896aedae.png)

**Comment by Nazarah** [comment]
@ralupopa  fixed

**Comment by ralupopa** [comment]
verified as fixed
