### ISSUE TITLE
Typo's observed on developer portal or platform of trust site

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#35]
# Describe the Pain you found while using Developer Portal

Page [https://developer.oftrust.net/guides/ontology-extension-guide/](https://developer.oftrust.net/guides/ontology-extension-guide/)
![image](https://user-images.githubusercontent.com/62647565/81919842-0575ae00-95e1-11ea-91dd-4908dc3ba34c.png)

Page [https://platformoftrust.net/en/pricing/](https://platformoftrust.net/en/pricing/)
![image](https://user-images.githubusercontent.com/62647565/81920014-4077e180-95e1-11ea-9e30-2ffad57ac1ef.png)

Page [https://developer.oftrust.net/apis/application/](https://developer.oftrust.net/apis/application/)
![image](https://user-images.githubusercontent.com/62647565/81920144-74eb9d80-95e1-11ea-9d79-0aa09709552d.png)

# Indicate the importance with a number
3
(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by ralupopa** [comment]
Page [https://developer.oftrust.net/guides/identities-and-links/](https://developer.oftrust.net/guides/identities-and-links/)
![image](https://user-images.githubusercontent.com/62647565/81920574-1115a480-95e2-11ea-9d97-3902835477ae.png)

This makes the link broken. It needs to be https://standards.oftrust.net/v1/Context/Identity/Device/Sensor/CarbonDioxideSensor

**Comment by Nazarah** [comment]
@ralupopa  fixed up the issues related to developer portal. Pirkko will fix the pricing page issue. You can test and close the issue.

**Comment by ralupopa** [comment]
Thanks @Nazarah 
Would be nice to keep the consistency in naming here 
![image](https://user-images.githubusercontent.com/62647565/82024681-d0c52d80-9698-11ea-99d2-5cb00bb166e2.png)
-> CarbonDioxideSensor

**Comment by Nazarah** [comment]
@ralupopa  fixed
