### ISSUE TITLE
Wrong links (to external app) in guide Integrate Data Source in 60 Minutes!

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#36]
# Describe the Pain you found while using Developer Portal
See guide [https://developer.oftrust.net/guides/integrate-data-source-60-minutes/](https://developer.oftrust.net/guides/integrate-data-source-60-minutes/)

![image](https://user-images.githubusercontent.com/62647565/81927148-d6186e80-95eb-11ea-9bb0-d6338b790faf.png)

![image](https://user-images.githubusercontent.com/62647565/81927290-10820b80-95ec-11ea-95e1-cef2e8a1ef09.png)

please validate these links. Current ones are not accessible for public. They should anchor actual sections from guide if possible or left without anchor.

# Indicate the importance with a number
2
(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by Nazarah** [comment]
@ralupopa  fixed

**Comment by ralupopa** [comment]
@Nazarah Sorry for returning to this, but there are 2 links which were missed update

Step 5 and step 6.1 from the second image above

**Comment by Nazarah** [comment]
@ralupopa  fixed
