### ISSUE TITLE
Improper ontology standard shared in some guides

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#37]
# Describe the Pain you found while using Developer Portal
Page [https://developer.oftrust.net/guides/identities-and-links/](https://developer.oftrust.net/guides/identities-and-links/) has mentions of Ontology Viewer
Also guide [https://developer.oftrust.net/guides/integrate-data-source-60-minutes/](https://developer.oftrust.net/guides/integrate-data-source-60-minutes/)

Example :
![image](https://user-images.githubusercontent.com/62647565/81930953-f8ad8600-95f1-11ea-8a2f-c970c4663623.png)

Please update these guides so that Ontology Viewer link is specifically [https://standards-ontotest.oftrust.net/](https://standards-ontotest.oftrust.net/) As confirmed with Roman this is the correct link, and do not include version to the shared link since it is subject to change. Server will redirect to latest available version
There should not be any link to direct to  https://platform-of-trust.wvfflife.now.sh/v1/ 

# Indicate the importance with a number
1
(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by Nazarah** [comment]
@ralupopa Fixed. Please check them and close the issue if all are correct.

However, the use of version couldn't be avoided entirely as some links required specification of particular identity context and link type. The pictures are given here. When the versioning changes, please open a separate issue mentioning changes that need to be made in the link. Thanks.
 
![Screen Shot 2020-05-15 at 9 17 06](https://user-images.githubusercontent.com/17976243/82018073-2abff600-968d-11ea-9215-0d2444f44b49.png)
![Screen Shot 2020-05-15 at 9 17 40](https://user-images.githubusercontent.com/17976243/82018079-2d225000-968d-11ea-99bc-89d44c32ec2c.png)

**Comment by Nazarah** [comment]
@ralupopa there is a label named `usability issue` in this repo. You can use this to markdown issues that are not necessarily a bug, but a more of a usability problem. like this issue.

**Comment by ralupopa** [comment]
@Nazarah  Please change links in guide [https://developer.oftrust.net/guides/integrate-data-source-60-minutes/](https://developer.oftrust.net/guides/integrate-data-source-60-minutes/) as well

![image](https://user-images.githubusercontent.com/62647565/82023415-ecc7cf80-9696-11ea-865e-69db36157548.png)

![image](https://user-images.githubusercontent.com/62647565/82023531-15e86000-9697-11ea-8ac4-82da9e325f8b.png)

![image](https://user-images.githubusercontent.com/62647565/82023644-3fa18700-9697-11ea-9214-43098b57ed2c.png)

**Comment by Nazarah** [comment]
@ralupopa  done
