### ISSUE TITLE
60 minutes guide 

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#38]
# Describe the Pain you found while using Developer Portal

https://developer.oftrust.net/guides/integrate-data-source-60-minutes/ 

I believe in this step the `<sensor_id>`/link/`<data_product_id>`  has to be updated by the user before that works. You need to replace those with actual IDs.  

<img width="1251" alt="Näyttökuva 2020-5-14 kello 15 06 50" src="https://user-images.githubusercontent.com/1927158/81932650-c6515800-95f4-11ea-8f3f-280cf67af4e0.png">

At least mention that in the guide. 

# Indicate the importance with a number

(1. Critical, 2. Important, 3. Nice-to-have)

1.

**Comment by Nazarah** [comment]
@kyyberi We use the following format to represent cURL requests made to APIs. However, I mentioned as a note in the guide to include the `@id`s of `sensor` and `room` in the vurl request. 

![Screen Shot 2020-05-15 at 9 30 23](https://user-images.githubusercontent.com/17976243/82018902-e0d80f80-968e-11ea-8f5c-d8a49e5f9e25.png)

**Comment by Nazarah** [comment]
@kyyberi  there is now label `usability issue` in the repo. you can use that one to report issues like this, which doesn't necessarily break the service, but more like correcting formats or small changes. :)

**Comment by kyyberi** [comment]
I would make it even more obvious what you are talking about in the NOTE. Something like this: 

NOTE: In the cURL request, use @ids of the `Sensor` {sensorId} and `Data Product` {dataProductId} of your choice.
