### ISSUE TITLE
[Ontology Viewer: Wishlist or Issue]

### ISSUE THREAD

**Issue by panupit** [PlatformOfTrust/collected-feedback#39]
# Are you making a wish?

I'm just testing this new feature!

## Tell us the importance in a number:
(1 --> Critical, 2 --> Important, 3 --> Nice to have)

# Are you reporting for a bug?

## To Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error

## Environment (please complete the following information):
Device: (e.g. desktop)

**Comment by Nazarah** [comment]
Done for testing purpose, closing the issue.
