### ISSUE TITLE
Link for Login API docs needs update in Identity and data discovery guide

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#42]
# Describe the Pain you found while using Developer Portal
Guide [https://developer.oftrust.net/guides/identity-and-data-discovery/#data-products-discovery](https://developer.oftrust.net/guides/identity-and-data-discovery/#data-products-discovery ) contains indications for user to get ID of his own identity. The link for Login API towards docs of trust does not have proper value for that section

![image](https://user-images.githubusercontent.com/62647565/82658173-397b4f80-9c2f-11ea-8eb1-094007142337.png)

Should be [https://docs.oftrust.net/#me](https://docs.oftrust.net/#me)

# Indicate the importance with a number
3
(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by Nazarah** [comment]
@ralupopa  fixed.
