### ISSUE TITLE
Broken link of standard in guide

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#47]
# Describe the Pain you found while using Developer Portal
See guide https://developer.oftrust.net/guides/identities-and-links/ section Request template for creating Temperature Sensor identity, the context link from ontology is broken (points to a 404) : 
![image](https://user-images.githubusercontent.com/62647565/85670426-8ee0cb80-b6c9-11ea-8a8a-341e23a62bfd.png)

# Indicate the importance with a number
2
(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by Nazarah** [comment]
@ralupopa  will be fixed as part of #48

**Comment by Nazarah** [comment]
@ralupopa  fixed.
