### ISSUE TITLE
Ontology viewer link to point to production version

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#50]
# Describe the Pain you found while using Developer Portal
On guides published before ontology was released ontology viewer has links towards ontotest environment.
now that ontology v2 production is published, guides should be updated to have production links: instead of base uri https://standards-ontotest.oftrust.net/v2/ should be https://standards.oftrust.net/v2/
Also, maybe the code examples the values for @context could be updated since they are either lifeengine of v1 platform of trust ontology.

Guides to update:
- https://developer.oftrust.net/guides/integrate-data-source-60-minutes/#step-3-create-a-group 

![image](https://user-images.githubusercontent.com/62647565/89790820-2cce0f80-db2b-11ea-8cc0-bd96b4dd10c9.png)

And on https://developer.oftrust.net/guides/identity-and-data-discovery/#data-products-discovery

![image](https://user-images.githubusercontent.com/62647565/89791996-aa464f80-db2c-11ea-9feb-2542caeb0d8d.png)

I have checked other guides and they were using production not ontotest, as expected.

An example from this guide https://developer.oftrust.net/guides/integrate-data-source-60-minutes/#step-3-create-a-group where context could be updated (Register an application):
![image](https://user-images.githubusercontent.com/62647565/89791139-8df5e300-db2b-11ea-8aa1-c02943319cde.png)

# Indicate the importance with a number
3
(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by ralupopa** [comment]
@Nazarah Thank you for the related fixes. Here is what I found:

1. The actual links of ontology viewer which **are still pointing towards ontotest:**
- see in section 4.1 of https://developer.oftrust.net/guides/integrate-data-source-60-minutes/#step-3-create-a-group => Ontology Viewer links
- see section 4.2 of https://developer.oftrust.net/guides/integrate-data-source-60-minutes/ 
- see at step 7 https://developer.oftrust.net/guides/integrate-data-source-60-minutes/#step-7-connect-data-product-to-a-sensor, Link for AtDataProduct 

2. In guide https://developer.oftrust.net/guides/identity-and-data-discovery/#identities-discovery I see that the example of linkContext is from v1 of ontology. Let's change it to v2 to be consistent with the rest?

![image](https://user-images.githubusercontent.com/62647565/91047974-99fd9c80-e623-11ea-89a4-6ce6fcff29fe.png)

3. About the context links from the examples, I see you have changed from lifeengine ones, but platform of trust v1 are still present. Would it be good to have the actual context links from v2?

![image](https://user-images.githubusercontent.com/62647565/91048204-f6f95280-e623-11ea-845e-9e4f6a94c3c0.png)

**Comment by Nazarah** [comment]
@ralupopa  done. If there is nothing more to fix, you can close the issue. :)

**Comment by ralupopa** [comment]
@Nazarah just one more I could spot : 
![image](https://user-images.githubusercontent.com/62647565/91837938-65a66380-ec55-11ea-9697-c9fd36c00a4f.png)

**Comment by Nazarah** [comment]
@ralupopa  sorry for the late fix. closing the issue. If new things are found, please reopen and tag me. :')
