### ISSUE TITLE
Broken link of identity Context in guide

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#51]
# Describe the Pain you found while using Developer Portal
See guide https://developer.oftrust.net/guides/identity-and-data-discovery/#identities-discovery when discovery request is exemplified with the query parameters, identityContext parameter has a link which goes to a 404 : https://standards.lifeengine.io/v1/Context/Identity/Thing/HumanWorld/System/BuiltEnvironment/Building/

![image](https://user-images.githubusercontent.com/62647565/89792717-9d762b80-db2d-11ea-9a14-7c0acc61d5ca.png)

# Indicate the importance with a number

(1. Critical, 2. Important, 3. Nice-to-have)
2

**Comment by ralupopa** [comment]
This has been fixed, so I close the issue here.

**Comment by Nazarah** [comment]
@ralupopa  I found a few more things links were still pointing at lifeengine. those have been fixed as well.
