### ISSUE TITLE
Pricing schema page should have example of using two plans 

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#54]
# Describe the bug
Example of how to use PricePlans is missing. 

# URL to page if exists
https://dataproduct.oftrust.net/schemas/dps-document-schema/priceplanobject 

# Expected behavior
Provide concrete JSON example how two or more PricePlan elements are used inside one data product. Eg there must be some Product level element ``Pricing`` etc under which the ``PricePlan`` element go.

**Comment by ralucaoanapopa** [comment]
Examples are for PricePlan only without Product level element Pricing element. keeping this open

**Comment by IrinaZayats** [comment]
Please find Product level example here
![image](https://user-images.githubusercontent.com/74544585/104412358-bec3c380-5574-11eb-9651-7ed4458563d2.png)
