### ISSUE TITLE
Data Product mockup example should have two price plans

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#55]
# Describe the bug
Current example of Data PRoduct mockup has just one PricePlan. In reality, it will have multiple. 

# URL to page if exists

https://dataproduct.oftrust.net/schemas/dps-document-schema

# Expected behavior
The mockup should indicate how that is achieved by using ``Pricing`` etc element under which the PricePlan elements are.

**Comment by ralucaoanapopa** [comment]
Example of Data Product not updated yet

**Comment by RomanSavran** [comment]
Data product mockup now contains several price plans, including subscription by period and consumption amounts.
