### ISSUE TITLE
What is "priceCurrent", "pricePurchase" and "priceSell" in Product element? 

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#57]
# Describe the bug
Pricing is defined with Priceplan elements. Having something pricing related in Product level is redundant. 

# URL to page if exists

https://dataproduct.oftrust.net/schemas/dps-document-schema/productobject

**Comment by ralucaoanapopa** [comment]
https://dataproduct.oftrust.net/schemas/dps-document-schema/productobject is 404 where did  examples from that moved?
Maybe https://dataproduct.oftrust.net/schemas/dps-document-schema ? But I don't find any priceCurrent, pricePurchase, priceSell
