### ISSUE TITLE
Which connector is used information missing from data product spec 

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#58]
# Describe the bug
Data Product Spec is missing a spot where it says which connector(s) is/are used. 

# URL to page if exists

# Expected behavior
Define infrastructure element or include connector attribute to other element. In the dirty sketch provided 8 months ago it was created with Infra element under which ``Connector`` element was placed

<img width="692" alt="Näyttökuva 2020-9-27 kello 18 20 36" src="https://user-images.githubusercontent.com/1927158/94368699-4680e180-00ee-11eb-8bce-3135dc8b3604.png">

**Comment by IrinaZayats** [comment]
Connector element is defined on data product root level. Please reference example below.

https://dataproduct.oftrust.net/schemas/dps-document-schema

![image](https://user-images.githubusercontent.com/74544585/104415433-ad7db580-557a-11eb-99bf-4533e308cd51.png)
