### ISSUE TITLE
Currency options should be based on existing standard

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#59]
# Describe the bug
Data Product Spec `Pricing` entity defines attribute `currency` as string without any kind of limatations or foundation. 

```
{
   "name":"Premium Package",
   "currency":"Euro",
   "unitGroup":"Transaction",
   "unit":"Transaction",
   "quantity":100000,
   "rate":100
}
``` 

# URL to page if exists

https://dataproduct.oftrust.net/schemas/dps-document-schema/priceplan

# Expected behavior
For the sake of clarity and to avoid misunderstandings, the options in `currency` should be based on standard such as https://en.wikipedia.org/wiki/ISO_4217 which provides 3 char codes for all circulating currencies. 
Add the information about standard used in the description of the attribute.

**Comment by ralucaoanapopa** [comment]
not updated yet

**Comment by IrinaZayats** [comment]
Updated on this page and main example as well
https://dataproduct.oftrust.net/schemas/dps-document-schema/priceplan
