### ISSUE TITLE
Sensors Presence and Quantity are not part of v2 standards

### ISSUE THREAD

**Issue by ralucaoanapopa** [PlatformOfTrust/collected-feedback#63]
In ontology v1 there were 2 Sensors which are not part of v2 family:
- https://standards.oftrust.net/v1/Context/Identity/Device/Sensor/PresenceSensor/
- https://standards.oftrust.net/v1/Context/Identity/Device/Sensor/QuantitySensor/

It was intended to not include them in v2 ontology?
There are connectors which have dataType Presence at least, so I guess it makes some sense to have them in v2 as well?

Sensors available atm in standard v2 
![image](https://user-images.githubusercontent.com/22395549/99073831-487c0280-25bf-11eb-973e-f5d208a87ecf.png)

## Tell us the importance in a number:
(1 --> Critical, 2 --> Important, 3 --> Nice to have)
2

**Comment by IrinaZayats** [comment]
@ralucaoanapopa they were moved to processes in v2 ontology
https://standards-ontotest.oftrust.net/v2/Context/Identity/Process/Measure/MeasurePresence/
https://standards-ontotest.oftrust.net/v2/Context/Identity/Process/Measure/MeasureQuantity/

**Comment by ralupopa** [comment]
Thanks @IrinaZayats 
This is about Measurement. So basically sensors for Presence and Quantity are not to be served in V2 I understand. If there will be need for some data products, sites for such they are to use the general : https://standards.oftrust.net/v2/Context/Identity/Equipment/Device/Sensor/, right?

**Comment by IrinaZayats** [comment]
@ralucaoanapopa  right. Because Presence and Quantity are not related to Sensors.
