### ISSUE TITLE
Can't access commercial site page with Data Products

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#65]
# Describe the Pain you found while using Developer Portal

Check guide https://developer.oftrust.net/guides/data-product-101/

![image](https://user-images.githubusercontent.com/62647565/104314100-9c349a80-54e1-11eb-975a-335794d8f7f1.png)

That link value is https://platformoftrust.net/en/data-products/ which is a 404 page

Should be https://platformoftrust.net/en/the-data-products/

# Indicate the importance with a number

(1. Critical, 2. Important, 3. Nice-to-have)

**Comment by Nazarah** [comment]
@ralupopa  fixed
