### ISSUE TITLE
[Insomnia Workspace Plugin]: Issue found

### ISSUE THREAD

**Issue by smitha-2020** [PlatformOfTrust/collected-feedback#69]
Unable to install : @platform-of-trust/insomnia-plugin-platform-of-trust plugin

Open Insomnia
Go to Application > Preferences > Plugins
Type "insomnia-plugin-customtimestamp"
Click "Install Plugin"

**Comment by ralupopa** [comment]
Hello,
What plugin are you trying to install? 
https://www.npmjs.com/package/@platform-of-trust/insomnia-plugin-platform-of-trust
or
https://www.npmjs.com/package/insomnia-plugin-customtimestamp

Also can you say what error you get? or what is the behavior exactly?

**Comment by smitha-2020** [comment]
https://www.npmjs.com/package/@platform-of-trust/insomnia-plugin-platform-of-trust

Failed to install @platform-of-trust/insomnia-plugin-platform-of-trust

There may be an issue with the plugin itself, as a note you can discover and install plugins from the Plugin Hub.
Additionl Information
Error: Yarn error warning @platform-of-trust/insomnia-plugin-platform-of-trust > jssha@2.4.2: jsSHA versions < 3.0.0 will no longer receive feature updates

    at file:///C:/Users/smith/AppData/Local/insomnia/app-2021.1.1/resources/app.asar/bundle.js:102243:16
    at ChildProcess.exithandler (child_process.js:295:7)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by jc487497** [comment]
@smitha-2020 I have faced this problem before. You should install the plugin manually by npm then copy that to Insomnia plugin folder. ` $ npm install @platform-of-trust/insomnia-plugin-platform-of-trust
`
