### ISSUE TITLE
API Profile resources section is hard to get a grip

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#8]
# Describe the Pain in using this API

The section listing resources for API in profile page is somewhat messy and hard to know what is there, it needs some UX design. It looks butt ugly. The correct information is there probably it's not "inviting"

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)

2. 

**Additional context**
<img width="1293" alt="Näyttökuva 2020-3-30 kello 16 30 49" src="https://user-images.githubusercontent.com/1927158/77918075-0efebd00-72a4-11ea-84a7-ed263ef0168c.png">

**Comment by kyyberi** [comment]
All the variety of things from spec files, to guides and community boards as well as feedback, is all spaghetti. Some sort of grouping might help.

**Comment by Nazarah** [comment]
@kyyberi  Thanks for issue. This would be fixed in upcoming weeks.

**Comment by ralupopa** [comment]
Beside the UX redesign, also check the actual links from some resources, currently they are pointing to wrong url.
These are all I could find on https://developer.oftrust.net/ domain

![image](https://user-images.githubusercontent.com/62647565/78266764-e0384f00-750e-11ea-944b-ee03ebdb3735.png)

**Comment by Nazarah** [comment]
@kyyberi  Resources section has been reorganized for all API profiles.
<img width="1415" alt="Screen Shot 2020-04-09 at 9 40 15" src="https://user-images.githubusercontent.com/17976243/78865438-4c064480-7a46-11ea-8de1-2b1fc3474281.png">

**Comment by Nazarah** [comment]
@ralupopa  you need to provide a detailed list of links and where they are in the developer portal. otherwise, it is impossible to find out and fix them all one by one. Please open a separate issue containing all broken links and their locations.

**Comment by ralupopa** [comment]
@Nazarah created #18
For the record, the image I put above is from a check broken links tool. Can be seen:
- actual link
- Linked from: the page where the link exists.
