### ISSUE TITLE
Identity API | parameter linkContext from /identities/v1/discovery can have a value without / despite documentation

### ISSUE THREAD

**Issue by ralupopa** [PlatformOfTrust/collected-feedback#9]
https://docs.oftrust.net/#identities-v1-discovery

**GET /identities/v1/discovery** 

Parameter **linkContext**  has specified The link context to traverse. The context MUST end with a forward slash /.

**Currently:** 
Can perform request with linkContext having value as : https://standards.oftrust.net/v1/Context/Link/BelongsTo

**Wanted:** 
Enforce validation as it is specified in documentation and as it already is for identityContext. 
When making request without the end / for linkContext, response should be consitent with how is for identityContext
`{
  "error": {
    "status": 422,
    "message": "Link context must end with a /"
  }
}`

**Comment by kyyberi** [comment]
There was some kind of debate whether there should always be a trailing slash in the end of endpoint or not. 

The source (https://restfulapi.net/resource-naming/) is not authorative but recommends that 

> Do not use trailing forward slash (/) in URIs. As the last character within a URI’s path, a forward slash (/) adds no semantic value and may cause confusion. It’s better to drop them completely.

**Comment by kyyberi** [comment]
To completely remove the issue, API gateway should remove the trailing slash before passing it to actual API. That way we do not need to worry about this.

**Comment by catalin-sbp** [comment]
@ralupopa In the meantime, until the updates suggested by @kyyberi will be implemented, we've updated a bit the description of that param in order to be more accurate

Please review this at your convenience and set the appropriate status for this issue - thank you.

**Comment by ralupopa** [comment]
![image](https://user-images.githubusercontent.com/62647565/81910194-487d5480-95d4-11ea-8ea0-4803b06f6525.png)
Closing then
